version: '3.5'

services:
  app:
    dns: 8.8.8.8
    build: .
    command: stack exec main
    working_dir: /app
    environment:
      DB_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: haskell_test
    depends_on:
      - postgres
    networks:
      - haskell-test
    ports:
      - "3000:3000"
  postgres:
    image: postgres
    command: createdb haskell_test -U postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      haskell-test:
        aliases:
        - localhost
networks:
  haskell-test:
    external: false
