name: haskell-test
version: 0.1.0.0
github: "realglebivanov/haskell-test"
license: BSD3
author: "Gleb Ivanov"
maintainer: "realglebivanov@gmail.com"
copyright: "2019 Gleb Ivanov"
description: Testing out JSON RPC and Persitent in Haskell

dependencies:
- base >= 4.7 && < 5
- json-rpc-server
- mtl
- bytestring
- aeson
- scotty

library:
  source-dirs: [app, domain]

executables:
  main:
    main: Main
    source-dirs: bin
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-test

  migrations:
    main: Migrations
    source-dirs: bin
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-test

tests:
  test:
    main: Spec
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-test
